### ISSUE TITLE
Tag the repo for each bosh release

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/cf-redis-release#1]
*deleted as unrelated*

**Comment by drnic** [comment]
Oh, sorry, the reason for the request for tags is that bosh-workspace looks for tags to get the right spiff templates. Currently it barfs if there are no tags; and I assume you'll start adding `templates` folder full of spiff templates one day.

**Comment by drnic** [comment]
Bump. Can you please git tag the repo when you cut new BOSH releases so that we can match the spiff templates to each release?

**Comment by drnic** [comment]
@tsaleh who is the right PM/eng lead to ping this to; to get it into the team's tracker? thanks

**Comment by tsaleh** [comment]
Hi @drnic - @benlaplanche is the person to talk to about this.

**Comment by benlaplanche** [comment]
@drnic i'll speak to the team and get back to you.

**Comment by benlaplanche** [comment]
@drnic we have a story in our backlog to start doing this going forwards. You cool if i close this issue or would you like me to leave it open until you have witnessed this happening?

**Comment by st3v** [comment]
Tags have been added for previous releases. Going forward our CI will tag each final release.
