### ISSUE TITLE
Make submodules https for public access

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/cf-redis-release#16]
I cannot sync the submodules to create dev releases with patches due to `git@` private submodules. Could you please change to `https://` submodules?

```
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:pivotal-cf/cf-redis-broker.git' into submodule path 'src/cf-redis-broker' failed
```

**Comment by tushar-dadlani** [comment]
This is fixed by https://github.com/pivotal-cf/cf-redis-release/pull/21
