### ISSUE TITLE
Redis Manifest with Sentinel Job

### ISSUE THREAD

**Issue by GuruprakashS** [pivotal-cf/cf-redis-release#22]
Hi,

Does the latest release of cf-redis-release support sentinel feature of redis. If yes, could you please provide the sample manifest with sentinel Job sections.

Thanks,
Guru.

**Comment by benlaplanche** [comment]
We only support a single node Redis, with no support for sentinel.

**Comment by gberche-orange** [comment]
@benlaplanche Would a contribution adding add multiple node support to cf-redis-release be likely to be accepted ? 

If so, is there recommendations/suggestions that could be used in designing such multi-node support ?

Thanks in advance,

Guillaume.

**Comment by benlaplanche** [comment]
Hi Guillaume, no it wouldn't be as it's nothing something i want to offer or support in the product at the moment.
