### ISSUE TITLE
Is there plan to support shared-plan?

### ISSUE THREAD

**Issue by mjsjinsu** [pivotal-cf/cf-redis-release#27]
HI thanks to this repo I can deploy cf-redis-release

1. I wonder If I make shared plan, How can I do?
As mentioned below, Is it right limitation?
https://docs.pivotal.io/redis/overview.html#service 

2. how to deploy multi redis_broker instance?
I can't see thing clearly expept multi dedicated-node deploying
+-------------------+---------+----------+-----------+
| VM                | State   | VM Type  | IPs       |
+-------------------+---------+----------+-----------+
| cf-redis-broker/0 | running | redis_z1 | 10.0.0.31 |
| dedicated-node/0  | running | redis_z1 | 10.0.0.32 |
+-------------------+---------+----------+-----------+

3. Is there no need to redis clustering?, such as p-mysql galera cluster
As i know redis backup data is stored in persistent disk
but when one of redis node occurs system failures, Is there any problem with the service?

**Comment by thereses** [comment]
1. Can you please add a bit more detail, not sure what you're asking?
2. Multiple brokers are not supported.
3. Clustering is not supported. If a node fails, it is restored. There will be no redis service while the node is restarting.
