### ISSUE TITLE
Dangerous silent purge service offering in deregistrer errand

### ISSUE THREAD

**Issue by poblin-orange** [pivotal-cf/cf-redis-release#28]
The broker-deregistrar errand purges the service offering 

```
cf purge-service-offering -f $BROKER_SERVICE_NAME
```

I understand its convenient for bosh release dev, but i believe its very dangerous to set this in the broker-deregistrer errand.
If production operator has to delete the a redis broker service with existing service instances, he should explicitly purge the service instances, before launching the errand

**Comment by thereses** [comment]
The deregistrar errand is only meant to be called during service deletion. I've added a note to the tracker issue to document this in the repo.

**Comment by mrosecrance** [comment]
We no longer run a purge and instead fail. Closing this issue
