### ISSUE TITLE
Extend the broker to support multiple plans

### ISSUE THREAD

**Issue by ealessandria-orange** [pivotal-cf/cf-redis-release#32]
Hi,

I was wondering if you would accept a contribution for broker plans portfolio extension (e.g. dedicated-small, dedicated-medium, dedicated-large)
Alternatively, would you accept that the broker could support some extensions (without being forked) ?

Thanks in advance

Eugenio

**Comment by thereses** [comment]
We are about to start building a new service broker that provides on demand provisioning https://docs.pivotal.io/on-demand-service-broker. With this broker we will offer multiple sized plans as well as the ability to configure some Redis properties.  
We don't want to extend the current service broker to provide more plans as the new service broker will do that.

**Comment by gberche-orange** [comment]
Thanks @thereses for your response. 

Will this new service broker have an open source strategy similar to https://github.com/pivotal-cf/cf-redis-release being a scaled down version of [Redis for PCF](https://docs.pivotal.io/redis/1-6/index.html), and be compatible with the use of CF opensource distribution from CF Foundation ? 

I understand that https://github.com/pivotal-cf-experimental/redis-example-service-adapter-release/blob/master/docs/example-manifest.yml is only an example for service authors targeting PCF deployments with ODS (on demand service broker), unless an opensource variant of ODS is in the plan ?
