### ISSUE TITLE
Merge option not there.

### ISSUE THREAD

**Issue by rahul221192** [pivotal-cf/cf-redis-release#34]
Migrating from redis  424 to 426 we checked that merge option has been removed from stubs and we have to manually  put values in the sample stubs.
Can you please confirm us whether same process will be followed is future releases?

**Comment by zvance** [comment]
Hi @rahul221192 

We've recently updated our docs and manifest templates to use the new BOSH2 structure. Manifest generation and deployment should be a lot simpler now.

We'll be removing the stubs from templates/ in the near future and corresponding generate manifest scripts. The README describes the new way to deploy cf-redis-release: https://github.com/pivotal-cf/cf-redis-release/blob/master/README.md

Thanks
