### ISSUE TITLE
Update redis to 3.2.4 to higher to address CVE and instability

### ISSUE THREAD

**Issue by gberche-orange** [pivotal-cf/cf-redis-release#38]
https://raw.githubusercontent.com/antirez/redis/3.2/00-RELEASENOTES mentions 

>  Redis 3.2.4     Released Mon Sep 26 08:58:21 CEST 2016
>
>Upgrade urgency CRITICAL: Redis 3.2 and unstable contained a security
>                          vulnerability fixed by this release.
>
>AFFECTED VERSIONS:
>All Redis 3.2.x versions are affected.

I understand cf-redis-release is running 3.2.1 vulnerable version (in the [master branch](https://github.com/pivotal-cf/cf-redis-release/blob/master/packages/redis/packaging#L4-L8) and in the latest [v436.3 tag](https://github.com/pivotal-cf/cf-redis-release/blob/v426.3.0/packages/redis/packaging#L4-L6)

Is there plans to update to redis 3.2.4 or 3.2.5 ?

**Comment by thereses** [comment]
Yes, we have a story in our backlog to update. This specific issue is not a vulnerability in our release though as we disable config.

**Comment by gberche-orange** [comment]
thanks @thereses for the additional precision on the vulnerability and the schedule

**Comment by zvance** [comment]
The latest redis release includes redis version 3.2.8. Thanks!
