### ISSUE TITLE
Bosh-Lite deploy of redis fails due to unresolved nodes

### ISSUE THREAD

**Issue by mminges** [pivotal-cf/cf-redis-release#42]
Bosh-lite install of redis fails on deploy after using the generate-deployment-manifest script in this repo

Steps to reproduce:
* Pre-existing BOSH-Lite CF deployment
* Run `./scripts/generate-deployment-manifest warden > ~/manifests/cf-redis.yml`
* `bosh upload release https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.143.0`
* Within cf-redis-release, `bosh upload release releases/cf-redis/cf-redis-424.yml`
* `bosh deployment ~/manifests/cf-redis.yml` and `bosh -n deploy`

Received the following error upon deploy:
```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 128
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'cf-redis-broker'. Errors are:
     - Unable to render templates for job 'cf-redis-broker'. Errors are:
       - Error filling in template 'registrar_settings.yml.erb' (line 3: Can't find property '["cf.nats.port"]')
```

Was able to resolve the issue by editing `templates/sample_stubs/meta-warden.yml` with the following properties under `meta.cf`:
```
    nats:
      host: 10.244.0.6
      port: (( .meta.nats.port ))
      username: (( .meta.nats.user ))
      password: (( .meta.nats.password ))
```

Posting this as a temporary work around if this is indeed a bug.

**Comment by BooleanCat** [comment]
Hi mminges.

We've recently updated our docs and manifest templates to use the new BOSH2 structure. Manifest generation and deployment should be a lot simpler now.

We'll be removing the stubs from `templates/` in the near future and corresponding generate manifest scripts. The README describes the new way to deploy cf-redis-release: https://github.com/pivotal-cf/cf-redis-release/blob/master/README.md

Please give it a try and we'd love to hear any feedback you have in the form of a new issue or PR.
