### ISSUE TITLE
redis can't bind ipv6 address on new bosh stemcells, fails to start

### ISSUE THREAD

**Issue by wbean1** [pivotal-cf/cf-redis-release#44]
stemcell: `bosh-stemcell-3363.20-openstack-kvm-ubuntu-trusty-go_agent`
cf-redis-release: `429.0.0`
routing-release: `0.152.0`

appears as though redis processes fail to bind, due to attempting to bind to both ipv4 & ipv6, but I'm guessing ipv6 networking has been disabled as of https://github.com/cloudfoundry/bosh/releases/tag/stable-3363.19

because of this, deployment fails with `Failed: 'dedicated-node/0 (ab055142-1184-4533-b26c-4c2065df3ae2)' is not running after update. Review logs for failed jobs: redis (00:03:49)`

from dedicated-node/0's /var/vcap/sys/log/redis/redis.log
```
Creating Server TCP listening socket *:6379: unable to bind socket
```
nothing else is listening on this port:
```
dedicated-node/ab055142-1184-4533-b26c-4c2065df3ae2:/var/vcap/sys/log/redis# netstat -anp |grep LISTEN
tcp        0      0 127.0.0.1:54321         0.0.0.0:*               LISTEN      11952/agent
tcp        0      0 127.0.0.1:33331         0.0.0.0:*               LISTEN      851/bosh-agent
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1805/sshd
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      12017/nginx.conf
tcp        0      0 0.0.0.0:55937           0.0.0.0:*               LISTEN      666/rpc.statd
tcp        0      0 127.0.0.1:2822          0.0.0.0:*               LISTEN      2258/monit
tcp        0      0 127.0.0.1:2825          0.0.0.0:*               LISTEN      851/bosh-agent
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      629/rpcbind
```

I believe the shared-node's redis processes had the same issue, I just didn't realize it til after I nuked my deployment and tried to recreate fresh... then encountered the same on dedicated-node as it was deployed first.

It doesn't seem like the redis bind address is configurable in the job params.

edit: confirmed that adding `bind 0.0.0.0` to `/var/vcap/store/redis/redis.conf` allows redis to startup successfully

**Comment by zvance** [comment]
Can you please use cf-redis-release v429.1.0? We've addressed this issue there.
