### ISSUE TITLE
The 'requirepass' property does not apply.

### ISSUE THREAD

**Issue by 7CHANHO** [pivotal-cf/cf-redis-release#46]
## ISSUE
The `requirepass` property does not apply.

## CONTEXT
I deployed cf-redis-release using the manifest with the requirepass attribute as shown below.
```
properties:
  redis:
    security:
      require_pass: "5a38c7c3-6cc2-434f-8713-f2344b77e47g"
```
However, this attribute did not apply to redis.
```
$ ./redis-cli -a 5a38c7c3-6cc2-434f-8713-f2344b77e47g
127.0.0.1:6379> info
NOAUTH Authentication required.
```
I checked two `redis.conf` files to analyze the cause.
First, the `redis.conf` configuration file in the `/var/vcap/jobs/dedicated-node/config/` path was applied as shown below.
```
$ cat /var/vcap/jobs/dedicated-node/config/redis.conf | grep requirepass
requirepass 5a38c7c3-6cc2-434f-8713-f2344b77e47g
```
However, the `redis.conf` configuration file in the `/var/vcap/store/redis/` path was not applied as shown below.
```
$ cat /var/vcap/store/redis/redis.conf | grep requirepass
requirepass 4a38c7c3-6cc2-434f-8713-f2344b77e47f
```

## QUESTION
1. Why does this happen? Is this my mistake?
2. How is  the `redis.conf` configuration file in the `/var/vcap/store/redis/` path configuration file generated? (e.g. the `redis.conf` configuration file in the `/var/vcap/jobs/dedicated-node/config/` path = cf-redis-release/jobs/dedicated-node/templates/redis.conf.erb)
3. How is the `requirepass` property generated? (Automatically generated values)

**Comment by mariantalla** [comment]
Hi @7CHANHO ,

Thank you for raising this issue. Out of curiosity, is this a fresh deployment of cf-redis or are you upgrading?

We investigated today and indeed the redis agent does not take `redis.security.require_pass` into consideration. Instead it generates a new random password for the instance (unless it can find an existing `/var/vcap/store/redis/redis.conf` in which case it will respect the previously created password for the instance.

The above behaviour is in place to prevent all `dedicated-node`s in a deployment from having the same password.

I will leave this issue open to track the future work that addresses the misleading manifest field.

cc @zvance @alamages

**Comment by 7CHANHO** [comment]
Thank you for your answers @mariantalla .

I am upgrading cf-redis deployment.

I try to configure high available dedicated node using HAProxy instead of Sentinel.
If I deploy HAProxy on a dedicated node that uses the same password, I think it is not perfect, but it is possible to configure HA appropriately. (I do not need replication because I use Redis simply for session storage.)

Is `redis.security.require_pass` will depricated?

**Comment by mariantalla** [comment]
Hi @7CHANHO ,

`redis.security.require_pass` will not take effect at all at the moment, a new password will be generated by the redis agent - so I'd recommend not configuring it in the manifest at all. If I'm reading your use case correctly that's desirable, is that right?

In the case of an upgrade, the password of the instance will remain the same (as it was before the upgrade).

**Comment by 7CHANHO** [comment]
Hi @mariantalla 

Unfortunately, If redis.security.require_pass is not take effect at all at the moment, It is not desirable to my use case.
Because I wanted to deploy two dedicated nodes using the same password for use in Active/Standby mode.
However, the explanation that the operation for preventing all dedicated-nodes in a deployment from having the same password is sufficiently understandable.

Perhaps I should look for other ways to configure Redis HA.
Thank you for your kindly reply.

**Comment by edwardecook** [comment]
Closing, as this isn't a feature we want to support. The cf-redis-release doesn't support deployment in any HA configurations (including Sentinel), it was designed to work as a single node solution. One aspect of that is the automatic generation of the password.
