### ISSUE TITLE
concourse github-resource says 'no versions available'

### ISSUE THREAD

**Issue by MinsuLim** [pivotal-cf/cf-redis-release#48]
Hi friends, 

I'm using concourse to get github release of pivotal-cf/cf-redis-release and deploy it to bosh.
But I got the message like below
 'no versions available'

'https://api.github.com/repos/pivotal-cf/cf-redis-release/releases' returns just  [ ]  while I expected 
lists of releases.

Is there anybody who using concourse github-release to get and deploy cf-redis-release??
Thank you for helping me in advance.

**Comment by MinsuLim** [comment]
I found that only users with push access receive listings for draft releases.
Could I get push access for this repository for just getting list of releases?

**Comment by mariantalla** [comment]
Hi @MinsuLim ,

Would you be able to work with getting cf-redis-release from bosh.io? http://bosh.io/releases/github.com/pivotal-cf/cf-redis-release?all=1

**Comment by edwardecook** [comment]
Closing this as we have created a new release from v434.02 although typically we just have release tags.
