### ISSUE TITLE
Stopping Monitored Services: Stopping services '[process-destroyer]' errored

### ISSUE THREAD

**Issue by cfmagnum** [pivotal-cf/cf-redis-release#50]
We are using cf-redis release 426.0.0. when we did small change like cf password change or stemcell version change and redeployed redis-service with chnages it gives error as follow:-

Action Failed get_task: Task 9567203f-dea9-416f-5632-e6a0b6bdc189 result: Stopping Monitored Services: Stopping services '[process-destroyer]' errored (00:01:15)

Error 450001: Action Failed get_task: Task 9567203f-dea9-416f-5632-e6a0b6bdc189 result: Stopping Monitored Services: Stopping services '[process-destroyer]' errored

We also tried to upgrade Redis to version 428.0.0. But getting the same error for 
process-destroyer as above.

could you please advice.

**Comment by cfmagnum** [comment]
Can you please inform us if there are  any findings on this issue.

**Comment by mariantalla** [comment]
Hi @cfmagnum,

What does `monit status` show for process-destroyer? Do the logs include any indication as to why stopping `process-destroyer` is unsuccessful?

**Comment by mariantalla** [comment]
Hi @cfmagnum , did you need any additional support with this?

We'll leave this open for another day and close it if we don't hear back. If this reoccurs in the future please feel free to open a new issue.
