### ISSUE TITLE
Push Changes to hide CF_ADMIN_PASSWORD to bosh.io

### ISSUE THREAD

**Issue by KeenanHoffman** [pivotal-cf/cf-redis-release#52]
Would it be possible to push the changes from `d78fd58da4cc6accd2bad23cb0923d54cb9c9156` to hide secrets to bosh.io 

Thanks,
Keenan

**Comment by edwardecook** [comment]
@KeenanHoffman the commit you've linked is already on master, we've also cut a release with that change on it, is that what you had in mind? Thanks

**Comment by geofffranks** [comment]
Yes, I believe the issue is just that the new releases aren't making it into bosh.io

**Comment by geofffranks** [comment]
Sounds like bosh.io might be broken due to https://github.com/pivotal-cf/cf-redis-release/blob/v432/jobs/no-op/spec#L5 ?

**Comment by terminatingcode** [comment]
@geofffranks @KeenanHoffman We just put in a fix to enable the newest releases to make it to bosh.io.
Let us know if you have anymore issues.
