### ISSUE TITLE
remove cf-redis/432.0.0 as it contains no-op job that is invalid

### ISSUE THREAD

**Issue by cppforlife** [pivotal-cf/cf-redis-release#53]
bosh.io tries to pick this version up, however, it cannot get the tarball built because job definition was invalid for no-op job.

**Comment by edwardecook** [comment]
Hi @cppforlife 

We will be happy to remove 432.0.0 given that it's failing to be picked up but we would be interested in exactly what you are running as part of your bosh.io automation to allow us to reproduce this issue and potentially avoid anything similar in the future. We haven't had any issues with this release when used as part of our tile or uploaded directly to a bosh director.

We also think it is likely that 432.0.1 will suffer from the same problem given it has the same no-op job in it so we will remove that too.

Let us know what you think.

**Comment by edwardecook** [comment]
v432.0.0 and v432.0.1 have been removed, we'd still be interested in hearing from you with regard to the questions above.

Thanks
