### ISSUE TITLE
Would it be possible to update bosh.io/releases to latest release

### ISSUE THREAD

**Issue by Scoobed** [pivotal-cf/cf-redis-release#54]
Would it be possible to update bosh.io/releases to latest release.  It looks to be a few versions behind this repo.  We are seeing an issue with the upstream smoke-test sample app where the buildpack is now being specified,  we get a random failure on the smoke-tests based on it trying to download all the versions of buildpacks.

**Comment by Scoobed** [comment]
Can someone please look at this issue.  the NOOP job was added in v432 and removed v433 it broke the bosh.io/releases ... in 433, the spacing is off in yml in the final noop job, which is causing the issue

**Comment by terminatingcode** [comment]
Hi @Scoobed 
We're trying to communicate with BOSH on the issue. We'll update the ticket once this is resolved.

**Comment by terminatingcode** [comment]
Resolved! The pipeline is fixed and the newest releases are now accessible via bosh.io
