### ISSUE TITLE
upload syslog-migration link is broken

### ISSUE THREAD

**Issue by SergeyMuha** [pivotal-cf/cf-redis-release#55]
Forth step is incorrect 
4.upload syslog-migration release 11
bosh upload-release https://github.com/pivotal-cf/syslog-migration-release/releases/download/v8/syslog-migration-11.tgz 
Link https://github.com/pivotal-cf/syslog-migration-release/releases/download/v8/syslog-migration-11.tgz  is broken. This release has been depricated in favor of syslog-release. 

Also "ops-file adds a GCP specific vm_extension: `public_ip`" there is no public_ip properties for gcp vm_extention. 
https://bosh.io/docs/google-cpi/#vm-types

**Comment by terminatingcode** [comment]
Hi @SergeyMuha 

This is much appreciated feedback. We've, sadly, let our README get out of date and there was delay between how we changed things with the syslog release and the `public_ip` vm extension.

I've updated the README to reflect that.

Thank you for bringing these to our attention and we'll try to be better open source citizens going forward!
