### ISSUE TITLE
Custom Space Names

### ISSUE THREAD

**Issue by sba30** [pivotal-cf/cf-redis-release#73]
Currently getting the following error running the redis smoke tests

Creating space cf-redis-smoke-tests-1-SPACE-09f61cc0310c2175 in org system as admin...
OK
Assigning role SpaceManager to user admin in org system / space cf-redis-smoke-tests-1-SPACE-09f61cc0310c2175 as admin...
The user exists in multiple origins. Specify an origin for the requested user from: 'uaa', 'ldap'
FAILED

To resolve am trying to set the space name to be a specific space name. However recently it seems this option has been made non-configurable - https://github.com/pivotal-cf/cf-redis-release/blob/2ac76cb681c41c5dfb326e22e75df9cd14e9b684/jobs/smoke-tests/templates/config.json.erb#L16

Can this be updated back to
'use_existing_space' => p('cf.space_name') ?

**Comment by MirahImage** [comment]
Hi, 

We've done exactly this. You should be able to specify an org and space for the smoke tests to run in now. Sorry for the slow response. 

Best,
