### ISSUE TITLE
README.md addition

### ISSUE THREAD

**Issue by jim80net** [pivotal-cf/cf-redis-release#9]
Hi there! 

We wanted to add the following text to the README. We'd like to know what the proper procedure for submitting a commit like this to this project. Should this be a PR, or just a commit to a certain branch? 

Thanks, 

Jim && Jonathan

```
## Deploying

### Subnet ACL

Allow at least the following: 
- [ ] Destination port 443 access to the service broker from the cloud controllers
- [ ] All destination ports on the redis dedicated nodes from the DEA network(s).

### DNS

Configure redis-broker((meta.environment)) to point to the static IP assigned 
to the redis-broker. 
```

**Comment by benlaplanche** [comment]
Pull Requests please.

**Comment by st3v** [comment]
We've added some info along those lines to the readme.
